//! Wayland idle source — `ext-idle-notify-v1` / `kwin_idle`.
//!
//! KWin (KDE) and Sway expose idle via the standard Wayland
//! protocols; **GNOME / Mutter does not** and is the case the
//! [`DegradedIdleSource`](super::DegradedIdleSource) handles.
//!
//! ### Status
//!
//! Implementing `ext-idle-notify-v1` in pure Rust is non-trivial:
//! a correct impl needs a Wayland connection, the protocol XML
//! generated by `wayland-scanner` (or a `wayland-protocols`
//! re-export), a connection-state event loop, and an event handler
//! callback that fires when the compositor pushes an idle event.
//! The "right" place for that is `wayland-client` + async
//! (calloop / tokio-integration).
//!
//! We ship the wrapper, set the right reliability flag, and accept
//! that the GNOME / mutter case flows through
//! [`DegradedIdleSource`](super::DegradedIdleSource) at the factory
//! level (GNOME is the explicit fallback target). The KWin / Sway
//! / wl-roots case will be wired in a follow-up commit.
//!
//! In the meantime, every call to `idle_time()` returns
//! `Duration::ZERO` with [`IdleReliability::Unreliable`]. The
//! engine keeps timer-only mode on (no pause/reset, honest UI
//! note) — exactly the contract we'd honour even once the
//! protocol plumbing is finished, because the protocol's events
//! aren't strongly typed for "active" vs "idle" and we want a
//! human to validate the wiring end-to-end before we trust it
//! for the focus-cycle reset decision.

use std::time::Duration;

use rewind_core::ports::{IdleError, IdleReliability, IdleSource};

/// Wayland idle source. See module docs.
#[derive(Debug, Clone, Copy, Default)]
pub struct WaylandIdleSource;

impl WaylandIdleSource {
    pub fn new() -> Self {
        Self
    }
}

impl IdleSource for WaylandIdleSource {
    fn idle_time(&self) -> Result<Duration, IdleError> {
        // Stub; the real protocol implementation lands in a
        // follow-up commit. Return ZERO so the engine can
        // still proceed on its own timer in `idle-policy.rs`'s
        // non-idle branches (and so the picker returns a usable
        // trait object).
        //
        // We deliberately do **not** return an error: a
        // successful "ok, I don't know yet" is the correct
        // shape while we wait for protocol events; an error
        // here would make the engine retry every tick and
        // spam the log.
        Ok(Duration::ZERO)
    }

    fn reliability(&self) -> IdleReliability {
        // `Unreliable`, not `Unavailable`, because once the
        // protocol events do flow we *will* have data — we
        // just don't want the engine to act on it for pause
        // / reset until a human has eyeballed it. Note the
        // engine treats both `Unreliable` and `Unavailable`
        // as "no pause/reset" (run **timer-only mode**), so
        // functionally we're equivalent to the degraded
        // path today.
        IdleReliability::Unreliable
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use rewind_core::ports::IdleSource;

    #[test]
    fn returns_zero() {
        let s = WaylandIdleSource::new();
        assert_eq!(s.idle_time().unwrap(), Duration::ZERO);
    }

    #[test]
    fn reliability_is_unreliable_not_unavailable() {
        // `Unreliable` is intentional: it signals "data will be
        // available once the protocol is implemented; the
        // engine should keep timer-only mode on but the source
        // itself is *alive*". See module docs.
        let s = WaylandIdleSource::new();
        assert_eq!(s.reliability(), IdleReliability::Unreliable);
    }

    #[test]
    fn never_errors() {
        let s = WaylandIdleSource::new();
        // The stub never returns an error — that's by
        // design (see impl). Real impl in a follow-up will
        // return `Transient` if the Wayland socket dies.
        for _ in 0..3 {
            assert!(s.idle_time().is_ok());
        }
    }

    #[test]
    fn is_default_and_copy() {
        let a: WaylandIdleSource = Default::default();
        let b = a; // Copy
        assert_eq!(a.reliability(), b.reliability());
    }
}
